server:
  port: 8008
spring:
  application:
    name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8005/eureka/
zuul:
  routes:
    greetingMessage:
      url: http://localhost:8002
ribbon:
  eureka:
    enabled: false
